#!/bin/sh
# Load AppRole credentials generated by vault-init (local dev only).
set -eu

if [ -f /bootstrap/app-approle.env ]; then
  set -a
  # shellcheck disable=SC1091
  . /bootstrap/app-approle.env
  set +a
fi

exec uvicorn app.main:app --host 0.0.0.0 --port 8000
